#import <PEGKit/PKParser.h>

enum {
    OHMCONDITIONPARSER_TOKEN_KIND_GE = 14,
    OHMCONDITIONPARSER_TOKEN_KIND_EQ,
    OHMCONDITIONPARSER_TOKEN_KIND_COMMA,
    OHMCONDITIONPARSER_TOKEN_KIND_LT,
    OHMCONDITIONPARSER_TOKEN_KIND_LE,
    OHMCONDITIONPARSER_TOKEN_KIND_OR,
    OHMCONDITIONPARSER_TOKEN_KIND_GT,
    OHMCONDITIONPARSER_TOKEN_KIND_NOTDISPLAYED,
    OHMCONDITIONPARSER_TOKEN_KIND_OPENPAREN,
    OHMCONDITIONPARSER_TOKEN_KIND_AND,
    OHMCONDITIONPARSER_TOKEN_KIND_NOT,
    OHMCONDITIONPARSER_TOKEN_KIND_CLOSEPAREN,
    OHMCONDITIONPARSER_TOKEN_KIND_NE,
    OHMCONDITIONPARSER_TOKEN_KIND_SKIPPED,
};

@interface OHMConditionParser : PKParser

@end

