#import <PEGKit/PKParser.h>

enum {
    OHMCONDITIONPARSER_TOKEN_KIND_GE_SYM = 14,
    OHMCONDITIONPARSER_TOKEN_KIND_DOUBLE_EQUALS,
    OHMCONDITIONPARSER_TOKEN_KIND_COMMA,
    OHMCONDITIONPARSER_TOKEN_KIND_LT_SYM,
    OHMCONDITIONPARSER_TOKEN_KIND_LE_SYM,
    OHMCONDITIONPARSER_TOKEN_KIND_OR_UPPER,
    OHMCONDITIONPARSER_TOKEN_KIND_GT_SYM,
    OHMCONDITIONPARSER_TOKEN_KIND_NOTDISPLAYED,
    OHMCONDITIONPARSER_TOKEN_KIND_OPENPAREN,
    OHMCONDITIONPARSER_TOKEN_KIND_AND_UPPER,
    OHMCONDITIONPARSER_TOKEN_KIND_BANG,
    OHMCONDITIONPARSER_TOKEN_KIND_CLOSEPAREN,
    OHMCONDITIONPARSER_TOKEN_KIND_NOT_EQUAL,
    OHMCONDITIONPARSER_TOKEN_KIND_SKIPPED,
};

@interface OHMConditionParser : PKParser

@end

